name: markblog

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: app
    depends_on:
      db:
        restart: true
        condition: service_healthy
    networks:
      - database
    ports:
      - 3000:3000
    env_file:
      - ./environments/db.env
      - ./environments/auth.env
      - ./environments/app.env

  db:
    build:
      context: .
      dockerfile: Dockerfile
      target: db
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 1s
      timeout: 5s
      retries: 10
    networks:
      - database
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - path: ./environments/db.env
        required: true
    user: postgres

networks:
  database: {}

volumes:
  postgres-data: {}
